### ISSUE TITLE
Language Property Undefined

### ISSUE THREAD

**Issue by imran300** [erikwibowo/Laravel-Brive#12]
Hello,
I just cloned your project and it is giving error on Lang
Do we have to do any configuration?

![Capture](https://github.com/erikwibowo/Laravel-Brive/assets/7050400/e61fc72b-6f0e-40b9-a8a8-b3a7d5907fb5)

**Comment by QueenZe** [comment]
it's not a big deal. 
if it's give error to your apps, please check the lang folder. and create it yourself.
