### ISSUE TITLE
Double 'of' di lang

### ISSUE THREAD

**Issue by QueenZe** [erikwibowo/Laravel-Brive#9]
Halo Mas Erik.
Saya menemukan ada 2 kata of dalam folder lang > app
Berikut saya sertakan screenshotnya. 

Mungkin bukan sesuatu yang mengganggu performa. tapi mungkin bisa jadi pertimbangan untuk dihapus.
Sudah saya PR juga. Semoga semakin baik kedepannya.

![image](https://github.com/erikwibowo/Laravel-Brive/assets/45986058/78d4b40a-4c4d-4171-be78-1db134129298)

**Comment by erikwibowo** [comment]
Halo terima kasih atas masukannya.

Sebaiknya kata tersebut jangan dihapus karena sudah dipakai di file resources/js/Components/Pagination.vue.
